version: '3.4'

services:
  web-whoami:
    image: emilevauge/whoami
    networks:
      - default
      - traefik-net
    deploy:
      replicas: 3
      labels:
        traefik.port: 80
        traefik.docker.network: "traefik-net"
        traefik.frontend.rule: "Host:whoami.swarm.lab.zengarden.se"
  web-nginx:
    image: kitematic/hello-world-nginx
    networks:
      - default
      - traefik-net
    deploy:
      replicas: 3
      labels:
        traefik.port: 80
        traefik.docker.network: "traefik-net"
        traefik.frontend.rule: "Host:nginx.swarm.lab.zengarden.se"

networks:
  traefik-net:
    external: true
